In [1]:
import laspy
import numpy as np
from tqdm import tqdm
from user_inputs import top, left, bottom, right, clipping, laz_file_path, clip_folder_path

In [2]:
laz_file_name = laz_file_path.split("\\")[-1].split(".")
clip_outlaz_file_name = laz_file_name[0] + "_clipped_8th_part." + laz_file_name[1]
print(laz_file_name)
print(clip_outlaz_file_name)


['C_37EN2', 'LAZ']
C_37EN2_clipped_8th_part.LAZ


**Checking if file reading working properly or not**

In [3]:
with laspy.open(laz_file_path) as f:
    input_point_count = f.header.point_count
    print(input_point_count)
    print("x_min, x_max: ", f.header.x_min, f.header.x_max)
    print("y_min, y_max: ", f.header.y_min, f.header.y_max)
    print("z_min, z_max: ", f.header.z_min, f.header.z_max)
print("top, left: ", top, left)
print("bottom, right: ", bottom, right)


1130794597
x_min, x_max:  85000.0 89999.999
y_min, y_max:  443750.0 449999.999
z_min, z_max:  -8.322000000000001 108.464
top, left:  449999.999 85000.0
bottom, right:  449218.74912500003 85624.999875


In [4]:
points_per_iter = int(input_point_count / 20)  ## restricting chunk iteration to 21 iterations
if clipping:

    with laspy.open(laz_file_path) as f:
        outfile_laz = laspy.open(clip_folder_path + "\\" + clip_outlaz_file_name, mode="w", 
                                 header=f.header)
        total_point_count = f.header.point_count
        count = 0
        for points in tqdm(f.chunk_iterator(points_per_iter), desc='Processing Chunks'):
            # For performance, we need to use copy
            # so that the underlying arrays are contiguous  ## from laspy doc
            
            x, y = points.x.copy(), points.y.copy()
            mask = (x >= left) & (x <= right) & (y >= bottom) & (y <= top)
            # print(f'Chunk Max X: {points.x.max()}, Min X: {points.x.min()}, Max Y: {points.y.max()}, Min Y: {points.y.min()}')  ## useless
            sub_points = points[mask].copy()
            print("\tsub_points: ", sub_points)
            outfile_laz.write_points(sub_points)
            count += len(points)
        
        outfile_laz.close()


Processing Chunks: 0it [00:00, ?it/s]

Processing Chunks: 1it [00:07,  7.32s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 2it [00:24, 13.13s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 3it [00:34, 11.62s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>
	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 15728986, point size: 34)>


Processing Chunks: 4it [00:46, 11.70s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 3013187, point size: 34)>


Processing Chunks: 6it [01:02,  9.62s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 7it [01:10,  9.18s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 8it [01:18,  8.81s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 9it [01:26,  8.56s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 10it [01:34,  8.21s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 11it [01:42,  8.15s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 12it [01:50,  8.07s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 13it [01:58,  8.06s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 14it [02:05,  7.84s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 15it [02:13,  7.82s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 16it [02:21,  7.89s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 17it [02:29,  7.86s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 18it [02:36,  7.66s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 19it [02:43,  7.51s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 21it [02:50,  5.27s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>
	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 21it [02:50,  8.14s/it]


reading the clipped points again to verify the point count

In [5]:
with laspy.open(clip_folder_path + "\\" + clip_outlaz_file_name) as f2:
    print(f2.header.point_count)

18742173


In [6]:
points_per_iter = int(input_point_count / 20)  ## restricting chunk iteration to 21 iterations
if clipping:

    with laspy.open(laz_file_path) as f:
        # outfile_laz = laspy.open(clip_folder_path + "\\" + clip_outlaz_file_name, mode="w", 
        #                          header=f.header)
        # total_point_count = f.header.point_count
        count = 0
        for points in tqdm(f.chunk_iterator(points_per_iter), desc='Processing Chunks'):
            # For performance, we need to use copy
            # so that the underlying arrays are contiguous  ## from laspy doc
            
            # x, y = points.x.copy(), points.y.copy()
            # mask = (x >= left) & (x <= right) & (y >= bottom) & (y <= top)
            # print(f'Chunk Max X: {points.x.max()}, Min X: {points.x.min()}, Max Y: {points.y.max()}, Min Y: {points.y.min()}')  ## useless
            # sub_points = points[mask].copy()
            # print("\tsub_points: ", sub_points)
            # outfile_laz.write_points(sub_points)
            # count += len(points)
            print(np.unique(points.classification))
        
        # outfile_laz.close()


Processing Chunks: 1it [00:06,  6.46s/it]

[ 1  2  6  9 14 26]


Processing Chunks: 2it [00:12,  6.42s/it]

[ 1  2  6  9 14 26]


Processing Chunks: 3it [00:20,  6.92s/it]

[ 1  2  6  9 26]


Processing Chunks: 4it [00:28,  7.23s/it]

[ 1  2  6  9 26]


Processing Chunks: 5it [00:35,  7.33s/it]

[ 1  2  6  9 26]


Processing Chunks: 6it [00:43,  7.38s/it]

[ 1  2  6  9 26]


Processing Chunks: 7it [00:52,  8.07s/it]

[ 1  2  6  9 14 26]


Processing Chunks: 8it [00:59,  7.67s/it]

[ 1  2  6  9 26]


Processing Chunks: 9it [01:07,  7.72s/it]

[ 1  2  6  9 26]


Processing Chunks: 10it [01:14,  7.67s/it]

[ 1  2  6  9 26]


Processing Chunks: 11it [01:22,  7.71s/it]

[ 1  2  6  9 26]


Processing Chunks: 12it [01:29,  7.39s/it]

[ 1  2  6  9 26]


Processing Chunks: 13it [01:36,  7.29s/it]

[ 1  2  6  9 26]


Processing Chunks: 14it [01:42,  7.02s/it]

[ 1  2  6  9 26]


Processing Chunks: 15it [01:50,  7.40s/it]

[ 1  2  6  9 26]


Processing Chunks: 16it [01:59,  7.66s/it]

[ 1  2  6  9 26]


Processing Chunks: 17it [02:06,  7.65s/it]

[ 1  2  6  9 26]


Processing Chunks: 18it [02:13,  7.25s/it]

[ 1  2  6  9 26]


Processing Chunks: 19it [02:20,  7.14s/it]

[ 1  2  6  9 26]


Processing Chunks: 21it [02:27,  7.01s/it]

[ 1  2  6  9 26]
[1 2]
