In [2]:
import laspy
import numpy as np
from tqdm import tqdm
from user_inputs import top, left, bottom, right, clipping, laz_file_path, clip_folder_path

In [3]:
laz_file_name = laz_file_path.split("\\")[-1].split(".")
clip_outlaz_file_name = laz_file_name[0] + "_clipped." + laz_file_name[1]
print(laz_file_name)
print(clip_outlaz_file_name)


['C_37EN2', 'LAZ']
C_37EN2_clipped.LAZ


**Checking if file reading working properly or not**

In [4]:
with laspy.open(laz_file_path) as f:
    input_point_count = f.header.point_count
    print(input_point_count)
    print("x_min, x_max: ", f.header.x_min, f.header.x_max)
    print("y_min, y_max: ", f.header.y_min, f.header.y_max)
    print("z_min, z_max: ", f.header.z_min, f.header.z_max)
print("top, left: ", top, left)
print("bottom, right: ", bottom, right)


1130794597
x_min, x_max:  85000.0 89999.999
y_min, y_max:  443750.0 449999.999
z_min, z_max:  -8.322000000000001 108.464
top, left:  449999.999 85000.0
bottom, right:  448437.49925 86249.99975


**Notes:** 
1. add extra_dim that is confidence

In [5]:
points_per_iter = int(input_point_count / 20)  ## restricting chunk iteration to 21 iterations
if clipping:

    with laspy.open(laz_file_path) as f:
        outfile_laz = laspy.open(clip_folder_path + "\\" + clip_outlaz_file_name, mode="w", 
                                 header=f.header)
        total_point_count = f.header.point_count
        count = 0
        for points in tqdm(f.chunk_iterator(points_per_iter), desc='Processing Chunks'):
            # For performance, we need to use copy
            # so that the underlying arrays are contiguous  ## from laspy doc
            
            x, y = points.x.copy(), points.y.copy()
            mask = (x >= left) & (x <= right) & (y >= bottom) & (y <= top)
            # print(f'Chunk Max X: {points.x.max()}, Min X: {points.x.min()}, Max Y: {points.y.max()}, Min Y: {points.y.min()}')  ## useless
            sub_points = points[mask].copy()
            print("\tsub_points: ", sub_points)
            outfile_laz.write_points(sub_points)
            count += len(points)
        
        outfile_laz.close()


Processing Chunks: 1it [00:06,  6.12s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 2it [00:13,  6.77s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 3it [00:21,  7.30s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 1295424, point size: 34)>
	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 46038322, point size: 34)>


Processing Chunks: 4it [00:37, 10.79s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 13020775, point size: 34)>


Processing Chunks: 6it [00:54,  9.39s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 7it [01:02,  8.70s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>
	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 13092784, point size: 34)>


Processing Chunks: 9it [01:18,  8.39s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 791118, point size: 34)>


Processing Chunks: 10it [01:25,  7.81s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 11it [01:31,  7.50s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 12it [01:38,  7.28s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 13it [01:45,  7.25s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 14it [01:52,  7.08s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 15it [01:59,  7.13s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 16it [02:07,  7.26s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 17it [02:14,  7.05s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 18it [02:20,  6.93s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 19it [02:27,  7.04s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


Processing Chunks: 21it [02:35,  7.39s/it]

	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>
	sub_points:  <PackedPointRecord(fmt: <PointFormat(1, 6 bytes of extra dims)>, len: 0, point size: 34)>


reading the clipped points again to verify the point count

In [9]:
with laspy.open(clip_folder_path + "\\" + clip_outlaz_file_name) as f2:
    print(f2.header.point_count)

74238423


In [10]:
points_per_iter = int(input_point_count / 20)  ## restricting chunk iteration to 21 iterations
if clipping:

    with laspy.open(laz_file_path) as f:
        # outfile_laz = laspy.open(clip_folder_path + "\\" + clip_outlaz_file_name, mode="w", 
        #                          header=f.header)
        # total_point_count = f.header.point_count
        count = 0
        for points in tqdm(f.chunk_iterator(points_per_iter), desc='Processing Chunks'):
            # For performance, we need to use copy
            # so that the underlying arrays are contiguous  ## from laspy doc
            
            # x, y = points.x.copy(), points.y.copy()
            # mask = (x >= left) & (x <= right) & (y >= bottom) & (y <= top)
            # print(f'Chunk Max X: {points.x.max()}, Min X: {points.x.min()}, Max Y: {points.y.max()}, Min Y: {points.y.min()}')  ## useless
            # sub_points = points[mask].copy()
            # print("\tsub_points: ", sub_points)
            # outfile_laz.write_points(sub_points)
            # count += len(points)
            print(np.unique(points.classification))
        
        # outfile_laz.close()


Processing Chunks: 1it [00:06,  6.64s/it]

[ 1  2  6  9 14 26]


Processing Chunks: 2it [00:19, 10.49s/it]

[ 1  2  6  9 14 26]


Processing Chunks: 3it [00:27,  9.04s/it]

[ 1  2  6  9 26]


Processing Chunks: 4it [00:34,  8.55s/it]

[ 1  2  6  9 26]


Processing Chunks: 5it [00:42,  8.34s/it]

[ 1  2  6  9 26]


Processing Chunks: 6it [00:50,  8.03s/it]

[ 1  2  6  9 26]


Processing Chunks: 7it [00:57,  7.80s/it]

[ 1  2  6  9 14 26]


Processing Chunks: 8it [01:05,  7.88s/it]

[ 1  2  6  9 26]


Processing Chunks: 9it [01:12,  7.56s/it]

[ 1  2  6  9 26]


Processing Chunks: 10it [01:19,  7.48s/it]

[ 1  2  6  9 26]


Processing Chunks: 11it [01:27,  7.57s/it]

[ 1  2  6  9 26]


Processing Chunks: 12it [01:36,  7.90s/it]

[ 1  2  6  9 26]


Processing Chunks: 13it [01:43,  7.64s/it]

[ 1  2  6  9 26]


Processing Chunks: 14it [01:50,  7.45s/it]

[ 1  2  6  9 26]


Processing Chunks: 15it [01:57,  7.43s/it]

[ 1  2  6  9 26]


Processing Chunks: 16it [02:04,  7.26s/it]

[ 1  2  6  9 26]


Processing Chunks: 17it [02:10,  6.92s/it]

[ 1  2  6  9 26]


Processing Chunks: 18it [02:16,  6.70s/it]

[ 1  2  6  9 26]


Processing Chunks: 19it [02:23,  6.73s/it]

[ 1  2  6  9 26]


Processing Chunks: 21it [02:30,  7.17s/it]

[ 1  2  6  9 26]
[1 2]
