In [1]:
import numpy as np
from helper_functions import recursive_split, generate_bins

[[0, 2], [2, 4], [4, 6], [6, 8], [8, 10]]
[[0, 2], [2, 4], [4, 6], [6, 8], [8, 10]]


In [3]:
recursive_split(85000.0, 443750.0, 90000.0, 450000.0, 2000, 2000)

[(85000.0, 443750.0, 86250.0, 445312.0),
 (85000.0, 445312.0, 86250.0, 446875.0),
 (85000.0, 446875.0, 86250.0, 448437.0),
 (85000.0, 448437.0, 86250.0, 450000.0),
 (86250.0, 443750.0, 87500.0, 445312.0),
 (86250.0, 445312.0, 87500.0, 446875.0),
 (86250.0, 446875.0, 87500.0, 448437.0),
 (86250.0, 448437.0, 87500.0, 450000.0),
 (87500.0, 443750.0, 88750.0, 445312.0),
 (87500.0, 445312.0, 88750.0, 446875.0),
 (87500.0, 446875.0, 88750.0, 448437.0),
 (87500.0, 448437.0, 88750.0, 450000.0),
 (88750.0, 443750.0, 90000.0, 445312.0),
 (88750.0, 445312.0, 90000.0, 446875.0),
 (88750.0, 446875.0, 90000.0, 448437.0),
 (88750.0, 448437.0, 90000.0, 450000.0)]

In [2]:
number = 10
bin_count = 5
result = generate_bins(number, bin_count)
print(result)


[[0, 2], [2, 4], [4, 6], [6, 8], [8, 10]]


In [12]:
74238423
number = 74238413
bin_count = 14
result = generate_bins(number, bin_count)
print(result)


[[0, 5302744], [5302744, 10605488], [10605488, 15908231], [15908231, 21210975], [21210975, 26513719], [26513719, 31816463], [31816463, 37119206], [37119206, 42421950], [42421950, 47724694], [47724694, 53027438], [53027438, 58330182], [58330182, 63632925], [63632925, 68935669], [68935669, 74238413]]


In [7]:
A = np.array([[1], [2], [8]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A, "\n",  B)

[[1]
 [2]
 [8]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
comparison_result = A == B

# Print the result
print("Comparison result:")
print(comparison_result)

Comparison result:
[[ True False False]
 [False False False]
 [False  True False]]


In [ ]:
son: shape-X
daughter: vectori