In [1]:
import numpy as np
from helper_functions import recursive_split, generate_bins

[[0, 2], [2, 4], [4, 6], [6, 8], [8, 10]]
[[0, 2], [2, 4], [4, 6], [6, 8], [8, 10]]


In [3]:
recursive_split(85000.0, 443750.0, 90000.0, 450000.0, 2000, 2000)

[(85000.0, 443750.0, 86250.0, 445312.0),
 (85000.0, 445312.0, 86250.0, 446875.0),
 (85000.0, 446875.0, 86250.0, 448437.0),
 (85000.0, 448437.0, 86250.0, 450000.0),
 (86250.0, 443750.0, 87500.0, 445312.0),
 (86250.0, 445312.0, 87500.0, 446875.0),
 (86250.0, 446875.0, 87500.0, 448437.0),
 (86250.0, 448437.0, 87500.0, 450000.0),
 (87500.0, 443750.0, 88750.0, 445312.0),
 (87500.0, 445312.0, 88750.0, 446875.0),
 (87500.0, 446875.0, 88750.0, 448437.0),
 (87500.0, 448437.0, 88750.0, 450000.0),
 (88750.0, 443750.0, 90000.0, 445312.0),
 (88750.0, 445312.0, 90000.0, 446875.0),
 (88750.0, 446875.0, 90000.0, 448437.0),
 (88750.0, 448437.0, 90000.0, 450000.0)]

In [2]:
number = 10
bin_count = 5
result = generate_bins(number, bin_count)
print(result)


[[0, 2], [2, 4], [4, 6], [6, 8], [8, 10]]


In [12]:
74238423
number = 74238413
bin_count = 14
result = generate_bins(number, bin_count)
print(result)


[[0, 5302744], [5302744, 10605488], [10605488, 15908231], [15908231, 21210975], [21210975, 26513719], [26513719, 31816463], [31816463, 37119206], [37119206, 42421950], [42421950, 47724694], [47724694, 53027438], [53027438, 58330182], [58330182, 63632925], [63632925, 68935669], [68935669, 74238413]]


In [7]:
A = np.array([[1], [2], [8]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A, "\n",  B)

[[1]
 [2]
 [8]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
comparison_result = A == B

# Print the result
print("Comparison result:")
print(comparison_result)

Comparison result:
[[ True False False]
 [False False False]
 [False  True False]]


In [ ]:
son: shape-X
daughter: vectori

In [3]:
import laspy
import numpy as np
from scipy.spatial import KDTree
from user_inputs import laz_file_path, clip_folder_path
from user_inputs import search_radius, nn_threshold, bin_count_nn
from helper_functions_useless import generate_bins, fraction_of_trues
import time
from tqdm import tqdm

In [4]:
laz_file_name = laz_file_path.split("\\")[-1].split(".")
clip_laz_file_name = laz_file_name[0] + "_clipped_8th_part." + laz_file_name[1]
clip_laz_path = clip_folder_path + "\\" + clip_laz_file_name
clip_laz_path

'D:\\Geomatics\\thesis\\RefineNet\\data\\AHN\\clipped\\C_37EN2_clipped_8th_part.LAZ'

In [5]:
laz = laspy.read(clip_laz_path)

In [6]:
print(f"number of points: {laz.header.point_count}")

number of points: 18742173


In [7]:
# printing out all the available dimensions in clipped laz file
for dimension in laz.point_format.dimensions:
    print(dimension.name)
print("\nunique classifications in clipped region: ", np.unique(laz.classification))

X
Y
Z
intensity
return_number
number_of_returns
scan_direction_flag
edge_of_flight_line
classification
synthetic
key_point
withheld
scan_angle_rank
user_data
point_source_id
gps_time
Amplitude
Reflectance
Deviation

unique classifications in clipped region:  [ 1  2  6  9 26]
